# Generated by Django 5.1 on 2026-02-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_player_id_alter_sponsor_id_alter_team_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='description',
        ),
        migrations.RemoveField(
            model_name='team',
            name='image',
        ),
        migrations.RemoveField(
            model_name='team',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='team',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sponsors',
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
