# Generated by Django 5.1 on 2026-03-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_team_description_remove_team_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(upload_to='static/images/player_sponsors/'),
        ),
    ]
