# Generated by Django 5.1 on 2026-06-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sponsor_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(upload_to='static/images/players/'),
        ),
    ]
