# Generated by Django 4.2.4 on 2023-12-15 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2023, 12, 15, 20, 41, 45, 143740, tzinfo=datetime.timezone.utc), max_length=350),
            preserve_default=False,
        ),
    ]
