# Generated by Django 5.1 on 2026-02-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='wordpress_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
